spring:
  datasource:
    url: jdbc:mysql://39.106.135.201:3306/dianping?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

server:
  port: 8080
  servlet:
    context-path: /user